server:
  port: 8082

spring:
  application:
    name: DragonKing
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: "jdbc:clickhouse://192.168.93.2:8123,192.168.93.2:8123/tutorial"
    username: "default"
    password: ""
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver


mybatis:
  mapperLocations: classpath:*.xml